'use client'

import { useActionState, useEffect, useState } from 'react'
import { resetPassword } from '@/app/actions/auth'
import { AuthField, AuthButton, AuthError } from '@/components/auth/auth-ui'
import { createClient } from '@/utils/supabase/client'

// Links generated from the web app's own forgot-password flow arrive here
// with a session cookie already set (PKCE code exchanged by /auth/callback).
// Links generated by the mobile app use the classic implicit flow instead —
// Supabase redirects straight here with the recovery tokens in the URL
// *hash* (`#access_token=...&type=recovery`), which a server route can never
// see, so we establish the session client-side before allowing the form.
type HashStatus = 'checking' | 'ready' | 'error'

function useRecoverySessionFromHash() {
  const [status, setStatus] = useState<HashStatus>('checking')
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const hash = window.location.hash.startsWith('#') ? window.location.hash.slice(1) : window.location.hash
    if (!hash) {
      setStatus('ready') // no hash — assume a cookie session already exists (web-initiated flow)
      return
    }

    const params = new URLSearchParams(hash)
    const hashError = params.get('error_description')
    if (hashError) {
      setError(hashError.replace(/\+/g, ' '))
      setStatus('error')
      return
    }

    const access_token = params.get('access_token')
    const refresh_token = params.get('refresh_token')
    if (!access_token || !refresh_token) {
      setStatus('ready')
      return
    }

    createClient().auth.setSession({ access_token, refresh_token }).then(({ error: setErr }) => {
      history.replaceState(null, '', window.location.pathname)
      if (setErr) {
        setError(setErr.message)
        setStatus('error')
      } else {
        setStatus('ready')
      }
    })
  }, [])

  return { status, error }
}

export default function ResetForm() {
  const [state, action, pending] = useActionState(resetPassword, undefined)
  const { status, error: hashError } = useRecoverySessionFromHash()

  if (status === 'checking') {
    return <p className="text-sm text-gray-500">Verifying your reset link...</p>
  }

  if (status === 'error') {
    return (
      <div className="space-y-4">
        <AuthError>{hashError ?? 'This reset link is invalid or has expired.'}</AuthError>
        <a href="/forgot-password" className="text-sm font-semibold text-pink-600 hover:text-pink-700">
          Request a new link
        </a>
      </div>
    )
  }

  return (
    <form action={action} className="space-y-4">
      <AuthField
        id="password"
        name="password"
        label="New password"
        type="password"
        required
        minLength={8}
        autoComplete="new-password"
        placeholder="••••••••"
        hint="Minimum 8 characters"
      />

      <AuthField
        id="confirm"
        name="confirm"
        label="Confirm new password"
        type="password"
        required
        minLength={8}
        autoComplete="new-password"
        placeholder="••••••••"
      />

      {state?.error && <AuthError>{state.error}</AuthError>}

      <AuthButton pending={pending} label="Update password" pendingLabel="Updating..." />
    </form>
  )
}
